### ISSUE TITLE
Sync with caldav server

### ISSUE THREAD

**Issue by beli3ver** [lfos/calcurse#14]
Hi,

I have a caldav server, is there a way to sync calcurses with it and when yes how?

Thanks

**Comment by misterunknown** [comment]
Did you see [this](https://github.com/lfos/calcurse/tree/master/contrib/caldav) already?

**Comment by beli3ver** [comment]
Yes but does it support more then one calendar?

**Comment by misterunknown** [comment]
Well, you can have several config files and pass them to the script, but I'm afraid that multiple calendars are not supported, yet. As far as I understand the script, it can work in two modes: keep-local and keep-remote. IMHO none of this modes fits your needs, because:
* keep-remote: the script deletes all local entries and gets a new list from the server (so multiple runs would delete the previous collected data)
* keep-local: the script deletes all entries on the server (!) and pushes the local entries to it. So this would be like a sync of all your calendars.

So, I'm afraid you have to wait for the author to implement this feature or hack it yourself.

**Comment by beli3ver** [comment]
Ok thanks for that

**Comment by lfos** [comment]
Marco is right. Currently, calcurse does not support accessing/modifying multiple calendars in parallel. You need separate data files.
