### ISSUE TITLE
Error when you go past December 2037

### ISSUE THREAD

**Issue by Noisytoot** [lfos/calcurse#159]
There is an error when you go past December 2037 which exits the program.

**Comment by lhca** [comment]
Could you be more specific? What is the error? How is it reproduced? Command line use or interactive? What version of calcurse? What is your OS?

**Comment by Noisytoot** [comment]
The error is
```
Please report the following bug:
utils.c: 395: failure in mktime
```

My OS is Chrome OS 70.0.3538.76 in developer mode.
Interactive use (although it is from the command line).
Calcurse version: 4.3.0.
Reproduce it by going past December 2037.

**Comment by lhca** [comment]
Thank you so much.

This is a delicate area: the end of Unix time in 2038, at least on 32-bit systems. It seems, though, that many 64-bit architectures still use a 32-bit `time_t` type. So the reason is that you have reached the end of time! But it's not handled very gracefully, I admit.

The problem is adressed in this commit 691d6b33 and will make it into the next release.
