### ISSUE TITLE
Inconsistent handling of empty prompts

### ISSUE THREAD

**Issue by lfos** [lfos/calcurse#213]
When creating a new appointment and entering an empty end time, the end time is ommited. When specifying the end date of a recurring event, you have to enter `0` to omit the date. Here, the empty string will cancel. I think we should allow to use the empty string to omit the end date (and keep `0`, just for backwards comnpatibility).

Generally, I wonder whether we should cancel processes if a user enters an empty string. It is an invalid input for many prompts and should display a warning, then repeat the prompt.

**Comment by lhca** [comment]
I tried to recreate the scenario you describe, but had quite a different and inexplicable experience.

Looking at the code (which is my own), the reason was obvious: an uninitialized variable. The fix is easy and the result is the desired consistency. There is no question of backwards compatibility; the bug was introduced in 4.4.0.

I have uploaded a fix (PR #214).

**Comment by lfos** [comment]
I tested your patch but the behavior with the patch applied is still exactly the same...

**Comment by lhca** [comment]
I didn't read carefully enough what you wrote and was misled. But I also think that you are mixing things up.

> When creating a new appointment and entering an empty end time, the end time is ommited. When specifying the end date of a recurring event, you have to enter `0` to omit the date. Here, the empty string will cancel. I think we should allow to use the empty string to omit the end date (and keep `0`, just for backwards comnpatibility).

The two cases are quite different. The end _time_ of an appointment cannot be compared with the end _date_ of a recurring event. The latter is better called the until date. It is treated just like the until date of a recurring appointment, which has nothing to do with the end time.

Omitting the end _time_ of an appointment gives you an instant appointment. Omitting the end _date_ gives you an endless recurring appointment (or event), almost the opposite. There is no inconsistency.

The wording is unfortunate and confusing: "end time" and "end date" are too close for comfort. 
They designate two different things which you would never guess from the terms. The solution is to improve the prompt text and use "until" and not "end date" or "duration".

**Comment by lfos** [comment]
If you do not agree it is inconsistent, let's say it is unintuitive instead.

If you want to create an appointment without an end time, you can just enter an empty duration. If you want to create an endless recurring event, you have to enter `0`. If anything, switching these two scenarios would make much more sense: a duration of `0` describes an item without an end time quite well, whereas interpreting the "until date" `0` as infinity seems quite arbitrary. I would just allow the empty string in both cases.

**Comment by lhca** [comment]
Agreed.

**Comment by lhca** [comment]
The empty string as default behaviour is not reflected in the built-in help messages (987fa9d).

`const char *msg_help_1 = _("Date: %s (year or month may be omitted). Endless duration: 0.");`
`const char *mesg_help_1 = _("Date: %s (year or month may be omitted). Endless duration: '0'.");`

should be

`const char *msg_help_1 = _("Date: %s (year or month may be omitted). Endless duration: [ENTER].");`
`const char *mesg_help_1 = _("Date: %s (year or month may be omitted). Endless duration: [ENTER].");`

I just realised that the empty string as valid input makes it impossible to guide the user by displaying the current value for updating in case of a recurrent item without until date. That's an argument against d659a8e.

**Comment by lfos** [comment]
> I just realised that the empty string as valid input makes it impossible to guide the user by displaying the current value for updating in case of a recurrent item without until date. That's an argument against [d659a8e](https://github.com/lfos/calcurse/commit/d659a8e2eec44bba08ec498912e5217b28c4409b).
I don't understand that comment. Could you please eloaborate?

**Comment by lhca** [comment]
When an existing parameter is edited (periodic save, recurrence rule, start or end time, description, ...) it makes sense to display the current value for editing. It provides a template that makes it easier for the user to change the parameter. Also, it provides a way of _viewing_ the parameters and just accept the values displayed, for example the recurrence rule parameters.

The until date of a recurrent item is different from other parameters in that it is _either_ a date _or_ is missing. The missing date must be denoted in some way. In principle anything could be used, but something meaningful is best.

Until now 0 (zero) has been used for both input and output, because that was the value used internally.

Now an empty string is used for both input and output. But the two could be different. While I agree that the empty string is fine for input, it is not very informative for output (viewing). Displaying 0 as until date at least conveyed something exceptional. The empty string conveys nothing.

I suggest that the empty string in `update_rept()` is replaced by the string "endless", and that it is accepted as input along with 0 and "".

**Comment by lfos** [comment]
I am not sure why you believe that the empty string is fine as an input but not as an output. I agree the empty string is "nothing", so I read the output as "the end date is nothing" or "the end date does not exist". There is no risk of somebody missing this information because the prompt heading is always there and there is the cursor.

If you really feel strongly about it, I can change the behavior back to `0` or add another special value, though.
