### ISSUE TITLE
Delay After Pressing ESC

### ISSUE THREAD

**Issue by Ad-An** [lfos/calcurse#217]
Let's say I try to create a new appointment and for some reason I want to cancel the creation of it by pressing ESC. Then there is a very noticeable lag between pressing the ESC and canceling the action.

Is this a bug? I don't see why this can be anything else. Is there any other reason for it?

**Comment by lfos** [comment]
Not really a bug. By default, ncurses adds a delay which allows you to enter escape sequences. You can turn this off by using the `ESCDELAY` environment variable, e.g. by using `ESCDELAY=0 calcurse` to run calcurse.

Since we do not seem to use this kind of escape sequences, I suggest set this timeout to zero automatically as part of the calcurse initialization routine (by adding `set_escdelay(0)` to `wins_init()`). Any objections?

**Comment by Ad-An** [comment]
Thank you, the first part of your response is totally understand. I don't quite understand the second part though about the initialization routine.

**Comment by lfos** [comment]
The second part is about setting `ESCDELAY=0` automatically when running calcurse. This means you would not have to set the environment variable. It also means you can no longer specify a delay greater than zero, even when using `ESCDELAY=10` since that setting always gets overridden. But since we do not use this kind of escape sequences in calcurse, this does not seem to hurt...

**Comment by Ad-An** [comment]
Ok thank you very much. My question was answered and I used your solution to my setup.

**Comment by lfos** [comment]
Let's keep this open until we make this the default behavior (or decide that we won't).

**Comment by Ad-An** [comment]
Oh I am sorry, I didn't know my question had greater implications. Just so you know I started using Calcurse very recently so my user experience may differ from that of more mature users. I don't want my unfamiliarity with the program to have an impact on its development.

**Comment by lfos** [comment]
You raised a legitimate concern. I think everybody will benefit from removing the timeout.

**Comment by lfos** [comment]
I pushed a patch to pu and will let it sit there for a while.

**Comment by lhca** [comment]
I would advise against this (e412010).

From the ncurses documentation (https://invisible-island.net/ncurses/man/curs_getch.3x.html):

> Keypad mode
If keypad is TRUE, and a function key is pressed, the  token  for  that function key is returned instead of the raw characters: ...

(Calcurse uses keypad mode to handle arrow keys, function keys, etc.)

>When a character that could be the beginning of a function key  is received  (which, on modern terminals, means an escape character), curses sets a timer.  If the remainder of the sequence does not come in within the designated time, the character is passed through; otherwise, the function key value is returned. For this reason, many terminals experience a delay between the time a user presses the escape key and the escape is returned to the program.

>In ncurses, the timer normally expires after the value in ESCDELAY (see curs_variables(3x)).

Setting ESCDELAY to zero means that any delay during an escape sequence will break that sequence up. That's very likely to happen, e.g. when calcurse and the terminal emulator are on different hosts connected by a network.

**Comment by lfos** [comment]
Thanks for bringing this up. I started implementing it as a configurable value instead but could not come up with an explanation for why we need another config option if we already have the environment variable; so I ended up dropping the patch instead. Maybe `ESCDELAY` should be documented/referenced somehwere, though.

**Comment by Ad-An** [comment]
Just out of curiosity, when you are writing a new appointment for example and you just want to cancel it without completing it, how you do it? You can't press q cause you are in writing mode so you just write the letter and ESC produces that delay which means that it is not the correct way.

**Comment by lhca** [comment]
You press ESC and have to live with the slight delay (why "not the correct way"?). It's a fact of life in applications that must be able to distinguish between an escape sequence produced by the keyboard and one produced by the user.

I strongly advise you _not_ to set the environment variable ESCDELAY to zero. The consequences may turn up in unexpected ways.

**Comment by lfos** [comment]
> You press ESC and have to live with the slight delay (why "not the correct way"?). It's a fact of life in applications that must be able to distinguish between an escape sequence produced by the keyboard and one produced by the user.
> 
> I strongly advise you _not_ to set the environment variable ESCDELAY to zero. The consequences may turn up in unexpected ways.

I don't think this is true. On most modern systems with calcurse running directly in a terminal, setting the escape delay to 0 just works fine.

**Comment by lfos** [comment]
You can also just press ESC twice really quickly (without having the decrease the delay) by the way.

**Comment by Ad-An** [comment]
Thank both of you. I started using the double ESC sequence which works great.

**Comment by concatime** [comment]
We should probably add a note in the manpage about `ESCDELAY`.
