### ISSUE TITLE
November 3rd repeats, causing display to be wrong for remainder of month

### ISSUE THREAD

**Issue by BehindTheBrain** [lfos/calcurse#233]
4.5.0 on Fedora 30
![november_days_wrong](https://user-images.githubusercontent.com/4184955/63198543-ad554f80-c040-11e9-9f03-2f8d4c0b227c.png)
The image shows the issue: November 3rd is repeated as a day, throwing off the days of the week for the rest of the month. It seems to fix itself at the end of the month.

**Comment by lhca** [comment]
This is caused by erroneous handling of Daylight Saving Time (DST). Apparently November 3 is the end of DST in your location.

The bug was reported on the calcurse bugs mailing list and has been fixed. A patch is available on branch pu (https://github.com/lfos/calcurse/commit/d6fd07785fe8072e6bbadc173e9d6a2e73efdcdd).
