### ISSUE TITLE
No such file or directory *~/.local/share/calcurse/caldav/lock*

### ISSUE THREAD

**Issue by roxlu** [lfos/calcurse#283]
I've just installed the calcurse package for ArchLinux and created a `~/.config/calcurse/caldav/config` file to setup CalDav synchronisation. When I run `calcurse-caldav --init=keep-remote` I get an error like:

```
$ calcurse-caldav --init=keep-remote
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 706, in <module>
    open(lockfn, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/roxlu/.local/share/calcurse/caldav/lock'
```
I can create that directory, but shouldn't it use the `~/.config/calcurse/caldav` directory instead?

**Comment by lfos** [comment]
The `~/.config/calcurse/caldav/` should contain configuration files while data goes in `~/.config/calcurse/caldav`. I think it is fair to argue that a lock file is data, not configuration.

That being said, I believe we should create the directory if it doesn't exist instead of erroring out.

@Nitroretro, any comments/opinion from your side?

**Comment by Nitroretro** [comment]
@lfos I think we should make calcurse-caldav automatically create the required directories if they are missing. The reason this didn't happen before is that the legacy caldav data directory was the same as the config directory which was created by the user.
