### ISSUE TITLE
Hide days without appointments?

### ISSUE THREAD

**Issue by jhilker1** [lfos/calcurse#312]
First off, I really enjoy using calcurse as a student - it really helps me keep myself organized as far as projects goes. However, I did have a question about it -  is it possible to hide days without any appointments in the interactive view? I'd love to be able to view my assignments and classes and such, without having to see any days where I might not have anything going on.

**Comment by lfos** [comment]
Great to hear that calcurse is useful to you!

The idea of hiding days without appointments has been proposed before (see #238) but is currently hard to implement due to subtleties in the UI. If you want to contribute to the discussion, you're more than welcome to do so in issue #238. I will be closing this one as a duplicate. Thanks!
