### ISSUE TITLE
Fastmail breaks calcurse-caldav

### ISSUE THREAD

**Issue by next-mad-hatter** [lfos/calcurse#337]
Problem is reproducible with current master (e3dd92e -- contents of calcurse-caldav is identical to 4.7.0 release version afaics).

When the href path contains url-special characters, calcurse-caldav cannot establish correct mapping between local and remote (possibly only those which were created locally) calendar items; this results in items being erroneously deleted or created.

To reproduce, create a calendar entry locally, then sync with a CalDAV server with a url-special character in the href path -- in particular, Fastmail puts `/dav/calendars/user@domain/` in there.  Upon next synchronization the local item will be removed, and upon yet next one the remote item as well.

As far as I can see, this is due to the path currently being escaped in return value of `push_object`, but not being escaped anywhere else, especially in `get_etags`.  I can see correct behaviour with `urllib.parse.quote` removed, but have not tested for possible regressions.

**Comment by lfos** [comment]
Interesting, thanks for the report!

Note that we didn't quote the `href` originally, the current behavior was introduced in commit e943b06 (URL encode href before saving to sync.db, 2017-09-06). @watersalesman might be able to provide more context.

Looking at the implementation, I wonder whether we should quote `href` earlier in push_object() instead, i.e., quote before using it anywhere instead of only quote for the sync DB entry.

@next-mad-hatter Could you try moving the urllib.parse.quote() to where `href` is originally defined (first line in push_object()) and don't quote in the return value? (You may have to reinitialize the sync DB and/or run at least twice after the change.)

**Comment by next-mad-hatter** [comment]
Merged https://github.com/lfos/calcurse/pull/358 solves this for me
