### ISSUE TITLE
vdir support ?

### ISSUE THREAD

**Issue by strk** [lfos/calcurse#35]
Any plan in supporting the VDIR storage format for calendar events ?
See https://vdirsyncer.pimutils.org/en/stable/vdir.html

**Comment by lfos** [comment]
Not yet. Patches are welcome, though!

**Comment by guygma** [comment]
I am also interested in this. Any sense of the kind of effort it would take at this point? It may provide more standards compliant caldav compatibility than the current contribution.

**Comment by lfos** [comment]
Well, I guess you would at least have to rewrite the calcurse-caldav script [1]. You can have a look to get an idea of what needs to be done.

[1] https://github.com/lfos/calcurse/blob/master/contrib/caldav/calcurse-caldav.py

**Comment by guygma** [comment]
That is one approach, but to me that seems like it would unnecessarily reinvent what vdirsyncer already does well. The problem of talking to a CalDAV server and maintaining a bi-directional synchronized copy of its contents is already solved. I had envisioned a translation between the vdir format and the internal format of calcurse (most simple); or, better yet, a direct implementation of reading from vdir text format instead of using the calcurse default backend.

**Comment by lfos** [comment]
True, importing and exporting from/to vdir sounds like a good idea. Reading and writing directly from/to vdir should be possible as well. If we decide to go that route, we should probably support that for iCal as well.

**Comment by guygma** [comment]
I could be mistaken on this, but I do not think there is much of a distinction made for iCal format -- at least if all you mean by that is files with the ".ics" extention. For vdirs, contacts are stored in ".vcf" and calendars are stored in ".ics" as per the standards of vCard and iCal, respectively. I presume todos are included in the iCal representation but I won't swear to that.

**Comment by lfos** [comment]
Mh, I have not looked into vdir yet. If that's really all that needs to be done, we might "support" vdir already, though. We do support iCal imports and exports.

**Comment by guygma** [comment]
Yeah, give it a look ([vdirsyncer](https://github.com/pimutils/vdirsyncer)). It is a very nice project. It sounds like it could be a straightforward implementation to streamline full support of vdirs, which inherently makes calcurse as compatible with CalDAV as vdirsyncer has implemented (which is quite complete).

I bumped into this all because both calcurses and [khal](https://github.com/pimutils/khal) are great projects but I'm not fully satisfied with the viewing experience on either of them and have been considering what approach I would like to take to solve that. If both were compatible with the same backend (i.e., vdirs) then a larger portion of the community could benefit from a standalone or plug-able curses-based monthly/weekly viewer that alleviates my nit-picky disappointments.

**Comment by lfos** [comment]
I can't look into it in detail due to lack of time. I'd be more than happy if anybody else could help out. If you have improvement suggestions on the viewing experience, I'd encourage you to open a feature request for that as well.

**Comment by Tonus1** [comment]
I believe it could be as easily scripted as 
rm -fR .calcurse/[apts,todo,notes/*] && for i in ~/Calendars_dir/*/*.ics; do calcurse -i $i; done

Of course, would have to avoid the question to view log.

**Comment by vxid** [comment]
@strk @lfos @guygma @Tonus1 I opened a PR with vdir support. Syncing works fine (assuming you configured vdirsyncer properly). Of course this is still very experimental so back up your data first if you want to give it a try.

**Comment by Tonus1** [comment]
Thanks a lot, I will have a look very soon !

**Comment by ploth** [comment]
Good job! Will definitely give it a try.

**Comment by strk** [comment]
I think that PR does too much.

Tipically one would have synchronization already setup, so no need to invoke vdirsyncer.
The only thing needed would be for Calcurse to support the VDIR format (independent from vdirsyncer)

I it is impossible for Calcurse to support VDIR natively it would take a synhconization but only between calcurse data and the vdir directory. In no case I see it useful for calcurse to _run_ vdirsyncer. It should be completely agnostic from vdirsyncer, IMHO.

That PR was merged already, even if it was marked as WIP, why so ?

**Comment by lfos** [comment]
calcurse does not support the VDIR format and will not support that anytime in the near future. calcurse itself does not run vdirsyncer. The PR is about adding a helper script which is an interface between the VDIR format and calcurse.

We could make that script synchronize between VDIR and calcurse only but then, using the script becomes more involved: you need to run the script to sync in one direction, then run vdirsyncer manually, then run the script again to sync in the other direction. Do you have any actual real-world application for that scenario?

The PR was merged because it was ready to be merged as discussed with @vxid and me.

**Comment by vxid** [comment]
@strk 
I agree that ideally calcurse should be fully compatible with the ical format and store its data that way. In that case, there would be no need to wrap vdirsyncer at all since it would work out of the box on the calcurse data directory.

The aim of this script is mainly to wrap calcurse import and export functions so that calcurse events are exported to individual ical files (as per vdir specification) and imported back again. The vdir sync part of the script is simply a call in between these import/export operations, and could easily changed by anything else.

Actually, specifying which program to run between these operations (vdirsyncer at a non-standard location, another program or possibly even nothing) could be an interesting addition to the script.

**Comment by Tonus1** [comment]
Hi,
I was wondering where this is documented. I didn't see it in the man page nor the changelog.

**Comment by vxid** [comment]
@Tonus1
Did you check the pu branch?

**Comment by Tonus1** [comment]
@vxid No, I will, thank you !

**Comment by Tonus1** [comment]
I had a look at the new script but I'm afraid it doesn't really match my needs.
I already use other programs that integrate well with my standalone vdirsyncer config. I would have prefer to use same vdir.

I am thinking about some script that would import at launch all ics files and export new events/appointments/todo when closing the app.

Not difficult at launch, might be somehow tricky for exporting new events...

**Comment by Tonus1** [comment]
That's what I want to try. Will do it in bash (when I will have little time ;-) ). Suggestions welcomed !
at launch :

- create/modify list of ics files > list.new  
- match new files and deleted ones with list.back > list.diff 
- move list.back > list.old
- move list.new > list.back
- backup apts/todo/(notes?) .back to .old and new to .back
- import .diff list to calcurse
- at close check diff between apps/todo/(notes?) and .back files 
- export new
- generate list.back
- launch vdirsyncer

**Comment by lfos** [comment]
Sounds similar to what @strk said. Maybe we should think about switching to the alternative implementation I described above? Make the script sync with the VDIR directory only. Have two modes: import from VDIR and export to VDIR. Do not interact with vdirsyncer at all.

**Comment by vxid** [comment]
@Tonus1 
I think the best solution would be to add three flags to `calcurse-vdirsyncer`:

- `--no-export` : disable calcurse data exports
- `--no-sync`: disable vdirsyncer synchronization
- `--no-import`: disable calcurse data imports

That way you can use all three pieces (export, import, sync) independently.

In your case, you would have a first hook on calcurse startup:
`calcurse-vdirsyncer --no-export --no-sync <your vdir>` to import all events from the vdir to calcurse on startup and then a second hook on exit `calcurse-vdirsyncer --no-import --no-sync <your vdir>` to write calcurse events to the vdir.

**Comment by strk** [comment]
> Do not interact with vdirsyncer at all.

+1

**Comment by vxid** [comment]
@lfos @strk @Tonus1 
Feel free to discuss possible improvements in #195

**Comment by lfos** [comment]
The new script (that is more flexible and does not depend on vdirsyncer) has been merged into master.
