### ISSUE TITLE
Some readline bindings such as "CTRL('U')" missing in getstring

### ISSUE THREAD

**Issue by hiqua** [lfos/calcurse#37]
In https://github.com/lfos/calcurse/blob/master/src/getstring.c#L178, a part of the readline/libedit library is reimplemented, but some bindings are missing, such as CTRL('U') (unix-line-discard according to `man readline` on Debian).

I am not 100% sure because of the comment that precedes the function definition, but it looks like these bindings could be handled by [libedit](http://thrysoee.dk/editline/) instead of being redefined manually.

**Comment by lfos** [comment]
The problem is that mixing readline or libedit with ncurses is fairly involved already, see [1]. And multi-threading makes this even harder. It would be nice to have the input handling done by an external library but I fear that actually implementing the interface properly would make the code more complex than the current implementation (which is the opposite of what one usually expects when replacing reimplemented functionality by an external tool)... Patches are welcome, though!

[1] http://invisible-island.net/ncurses/ncurses.faq.html#readline_library
[2] https://stackoverflow.com/questions/691652/using-gnu-readline-how-can-i-add-ncurses-in-the-same-program

**Comment by hiqua** [comment]
I see, it is probably not worth it then, and I don't think I could do it myself. However please see #40 for the implementation of CTRL-U.
